# Generated by Django 3.1.2 on 2021-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20210813_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='lestName',
            new_name='lastName',
        ),
    ]
