# Generated by Django 3.1.2 on 2021-08-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20210813_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
    ]
